services:
  api-service:
    build:
      dockerfile: docker/staging/Dockerfile
      context: api/
    depends_on:
      - proxy-service
    ports:
      - 8000:8000
    env_file:
      - api/docker/staging/staging.env
    networks:
      - stock-app-net

  proxy-service:
    build:
      dockerfile: Dockerfile
      context: proxy/
    networks:
      - stock-app-net

networks:
  stock-app-net:
    driver: bridge
